src/Entity/User/Actor.php
<?php

namespace App\Entity\User;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Actor AccountManager
 *
 * Cette classe permet de manager les attributs du propriétaire principal d'un compte.
 *
 * @package    App\Entity\User
 * @author     Marius Stanislas KEMAYOU DJEUMENI <kdms1990@gmail.com>
 *
 * @ORM\Table(name="app_user_actor")
 * @ORM\Entity(repositoryClass="App\Repository\User\ActorRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Actor extends AbstractHuman
{
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="last_connection_date", type="datetime", nullable=true)
     */
    protected $lastConnectionDate;
    /**
     * @var string
     *
     * @ORM\Column(type="string",name="matricule", length=190, nullable=true)
     * @Assert\Length(max=190)
     */
    private $matricule;
    /**
     * @var \App\Entity\User\Access
     *
     * @ORM\OneToOne(targetEntity="App\Entity\User\Access", inversedBy="actor", cascade={"persist"},fetch="EAGER")
     * @ORM\JoinColumn(nullable=true, onDelete="cascade")
     * @Assert\Valid()
     */
    private $access;
    /**
     * @var \App\Entity\User\ActorMember[]
     *
     * @ORM\OneToMany(targetEntity="App\Entity\User\ActorMember", mappedBy="member",
     *      cascade={"persist","remove"}, fetch="LAZY")
     */
    private $actorRoles;

    /**
     * Actor constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->locationRoles   = new ArrayCollection();
        $this->actorRoles      = new ArrayCollection();
        $this->evaluationRoles = new ArrayCollection();
    }

    /**
     * Return next sequence of entity code
     *
     * @return string
     */
    public static function getSequence()
    {
        return 'app.entity.user.actor';
    }

    /**
     * @return string
     */
    public function getMatricule()
    {
        return $this->matricule . "";
    }

    /**
     * @param string $matricule
     *
     * @return Actor
     */
    public function setMatricule($matricule)
    {
        $this->matricule = $matricule;
        return $this;
    }

    /**
     * @return string|null
     * @Groups("item:read")
     * @Groups("item:list")
     */
    public function getLastConnectionDateValue()
    {
        if ($this->getDateAdd() && $this->getLastConnectionDate())
            return $this->getLastConnectionDate()->format('c');
        return null;
    }

    /**
     * Get $lastConnectionDate
     *
     * @return \DateTime
     */
    public function getLastConnectionDate()
    {
        return $this->lastConnectionDate;
    }

    /**
     * Set $lastConnectionDate
     *
     * @param \DateTime $lastConnectionDate
     *
     * @return $this
     */
    public function setLastConnectionDate($lastConnectionDate)
    {
        $this->lastConnectionDate = $lastConnectionDate;

        return $this;
    }

    /**
     * Remove actorRole
     *
     * @param \App\Entity\User\ActorMember $actorRole
     */
    public function removeActorRole(ActorMember $actorRole)
    {
        $this->actorRoles->removeElement($actorRole);
    }

    /**
     * Get actorRoles
     *
     * @return \Doctrine\Common\Collections\Collection|\App\Entity\User\ActorMember[]
     */
    public function getActorRoles()
    {
        return $this->actorRoles;
    }

    /**
     * @param ArrayCollection $items
     *
     * @return $this
     */
    public function setActorRoles(ArrayCollection $items)
    {
        $this->actorRoles->clear();
        foreach ($items as $item)
            $this->addActorRole($item);
        return $this;
    }

    /**
     * Add actorRole
     *
     * @param \App\Entity\User\ActorMember $actorRole
     *
     * @return $this
     */
    public function addActorRole(ActorMember $actorRole)
    {
        $actorRole->setMember($this);
        $this->actorRoles[] = $actorRole;

        return $this;
    }

    /**
     * Email de connexion
     *
     * @return string
     * @Groups("item:read")
     * @Groups("item:list")
     */
    public function getEmail()
    {
        if ($this->getAccess())
            return $this->getAccess()->getEmail();
        return '';
    }

    /**
     * @return \App\Entity\User\Access
     */
    public function getAccess()
    {
        return $this->access;
    }

    /**
     * @param \App\Entity\User\Access $access
     *
     * @return Actor
     */
    public function setAccess(Access $access = null)
    {
        $this->access = $access;
        return $this;
    }

    /**
     * Ce permet d'être toujours présent dans le résultat d'une api.
     * Cela permet l'autocomplétion dans une liste déroulante
     *
     * @return string
     * @Groups("item:read")
     * @Groups("item:list")
     */
    public function getLabel()
    {
        return $this->getFullname();
    }

    /**
     * @return string
     */
    public function getFullname()
    {
        return $this->getFirstname() . ' ' . $this->getLastname();
    }
}

src/Controller/Business/Front/IndexController.php
<?php

namespace App\Controller\Business\Front;

use App\Contracts\TokenGeneratorInterface;
use App\Controller\AbstractFrontController;
use App\Entity\Business\Url;
use App\Form\Business\UrlType;
use Symfony\Component\Form\FormError;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;


/**
 * Class IndexControllerAbstract
 *
 * @link       http://github.com/kdms90
 *
 * @since      2.0.0
 * @package    App\Controller
 * @subpackage App\Controller\Front
 * @author     Marius Stanislas KEMAYOU DJEUMENI <kdms1990@gmail.com>
 */
class IndexController extends AbstractFrontController
{
    /**
     * Add short link
     *
     * @param \App\Contracts\TokenGeneratorInterface $tokenGenerator
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function index(TokenGeneratorInterface $tokenGenerator)
    {
        $url  = new Url();
        $form = $this->createForm(UrlType::class, $url);
        // 2) handle the submit (will only happen on POST)
        $form->handleRequest($this->request);
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $token = strtolower($tokenGenerator->generateToken(4));
                $url->setRewrited($token);
                try {
                    $this->em->getConnection()->beginTransaction();
                    $this->em->persist($url);
                    $this->em->flush();
                    $this->em->clear();
                    $this->em->getConnection()->commit();
                    $data['form'] = $this->renderView('business/front/index/ajax/confirm-url.html.twig', [
                        'url'         => $url,
                        'rewritedUrl' => $this->generateUrl('app_business_front_url_find', ['token' => $token], UrlGeneratorInterface::ABSOLUTE_URL),
                    ]);
                    return $this->json($data);
                } catch (Exception $e) {
                    $this->em->getConnection()->rollBack();
                    $form->addError(new FormError($e->getMessage()));
                    $data['form'] = $this->renderView('business/front/index/ajax/form.html.twig', [
                        'form' => $form->createView(),
                    ]);
                    return $this->json($data);
                }
            }
            $data['form'] = $this->renderView('business/front/index/ajax/form.html.twig', [
                'form' => $form->createView(),
            ]);
            return $this->json($data);
        }
        return $this->render('business/front/index/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * Redirect to orginal link and increase total views
     *
     * @param string|null $token
     * @return \Symfony\Component\HttpFoundation\JsonResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function find(string $token = null)
    {
        $url = $this->em->getRepository(Url::class)->findOneBy(['rewrited' => $token]);
        if (!$url)
            return $this->redirectToRoute("app_foundation_front_homepage");

        try {
            $url->increaseViews();
            $this->em->getConnection()->beginTransaction();
            $this->em->persist($url);
            $this->em->flush();
            $this->em->clear();
            $this->em->getConnection()->commit();
            return $this->redirect($url->getOriginal());
        } catch (\Exception $e) {
            $this->em->getConnection()->rollBack();
            return $this->redirectToRoute("app_foundation_front_homepage");
        }
    }
}

src/Controller/Foundation/Front/EmbedController.php
<?php

namespace App\Controller\Foundation\Front;

use App\Controller\AbstractFoundationController;
use App\Entity\Blog\Post;
use App\Entity\Business\About;
use App\Entity\Business\Service;
use App\Entity\CmsPage;
use App\Entity\Parameter;

/**
 * Class IndexController
 *
 * @link       http://github.com/kdms90
 *
 * @since      2.0.0
 * @package    App\Controller
 * @subpackage App\Controller\Front
 * @author     Marius Stanislas KEMAYOU DJEUMENI <kdms1990@gmail.com>
 */
class EmbedController extends AbstractFoundationController
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function defaultMeta()
    {
        return $this->render('foundation/front/embed/default-meta.html.twig', []);
    }
}

src/Controller/Foundation/Front/IndexController.php
<?php

namespace App\Controller\Foundation\Front;

use App\Contracts\ControllerInterface;
use App\Controller\AbstractFrontController;


/**
 * Class IndexControllerAbstract
 *
 * @link       http://github.com/kdms90
 *
 * @since      2.0.0
 * @package    App\Controller
 * @subpackage App\Controller\Front
 * @author     Marius Stanislas KEMAYOU DJEUMENI <kdms1990@gmail.com>
 */
class IndexController extends AbstractFrontController implements ControllerInterface
{    /**
     * Affiche la page accueil MKonnected
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function index()
    {
        return $this->render('foundation/front/index/index.html.twig', []);
    }
}

src/Controller/User/Front/RegistrationController.php
<?php

namespace App\Controller\User\Front;

use App\Controller\AbstractFrontController;
use App\Entity\User\Access;
use App\Form\User\AccessType;
use App\Util\Authenticator;
use Exception;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * Class RegistrationController
 * @package App\Controller\User\Front
 */
class RegistrationController extends AbstractFrontController
{
    /**
     * @param \App\Util\Authenticator $authenticator
     * @param \Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface $passwordEncoder
     * @return \Symfony\Component\HttpFoundation\JsonResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function register(Authenticator $authenticator, UserPasswordHasherInterface $passwordEncoder)
    {
        $access = new Access();
        $form   = $this->createForm(AccessType::class, $access, ['isFront' => true]);
        // 2) handle the submit (will only happen on POST)
        $form->handleRequest($this->request);
        if ($form->isSubmitted()) {
            $plainPassword = $form->get('plainPassword')->get('mainField')->getData();
            if (empty($plainPassword))
                $form->get('plainPassword')->get('mainField')->addError(new FormError($this->text->trans('Veuillez entrer un mot de passe', [], 'actor')));
            else if (strlen($plainPassword) < 6) {
                $form->get('plainPassword')->get('mainField')->addError(new FormError($this->text->trans('Le mot de passe doit avoir au moins 6 caractères', [], 'actor')));
            }
            if ($form->isValid()) {
                $actor   = $access->getActor();
                $access->addRole('ROLE_SUPER_ADMIN');
                $access->setConfirmationToken($this->tokenGenerator->generateToken());
                // 3) Encode the password (you could also do this via Doctrine listener)
                $password = $passwordEncoder->hashPassword($access, $access->getPlainPassword());
                $access->setPassword($password);
                try {
                    $this->em->getConnection()->beginTransaction();
                    $this->em->persist($actor);
                    $this->em->persist($access);
                    $this->em->flush();
                    $this->em->clear();
                    $this->em->getConnection()->commit();
                    $data['form']       = $this->renderView('user/front/registration/ajax/confirm-email.html.twig', [
                        'email' => $access->getEmail(),
                    ]);
                    return $this->json($data);
                } catch (Exception $e) {
                    $this->em->getConnection()->rollBack();
                    $form->addError(new FormError($e->getMessage()));
                    $data['form'] = $this->renderView('user/front/registration/ajax/form.html.twig', [
                        'form' => $form->createView(),
                    ]);
                    return $this->json($data);
                }
            }
            $data['form'] = $this->renderView('user/front/registration/ajax/form.html.twig', [
                'form' => $form->createView(),
            ]);
            return $this->json($data);
        }
        return $this->render('user/front/registration/register.html.twig', [
            'form' => $form->createView(),
        ]);
    }


    /**
     * Receive the confirmation token from user email provider, login the user.
     *
     * @param \App\Util\Authenticator $authenticator
     * @param string $token
     *
     * @return Response
     */
    public function confirm(Authenticator $authenticator, $token)
    {
        $userManager = $this->em->getRepository('App:User\Access');
        $user        = $userManager->findOneBy(['confirmationToken' => $token]);
        if (null === $user) {
            throw new NotFoundHttpException(sprintf('The user with confirmation token "%s" does not exist', $token));
        }
        $user->setConfirmationToken(null);
        $user->setIsActive(true);
        try {
            $this->em->flush($user);
            $authenticator->authenticate($user);
            return $this->redirectToRoute('app_user_front_profile');
        } catch (Exception $e) {
        }
    }

}

templates/foundation/front/embed/counters-content.html.twig
<section class="counters-one">
    {% if enabledTitle %}
        <h3 class="text-center text-white"><span class="circle-mark"></span> Les chiffres parlent d'eux-même</h3>
    {% endif %}
    <div class="container">
        <div class="counters-one__box">
            <ul class="row list-unstyled">
                <li class="col-md col-4 projectsCount">
                    <p class="counter-one__text">
                        <span class="d-block one">
                            Plus de <span class="font-weight-bold">{{ projects_done }}</span>
                        </span>
                        <span class="d-block two">Projets réalisés</span>
                        <span class="d-block three">avec success</span>
                    </p>
                </li>
                <li class="col-md col-4 countriesCount">
                    <p class="counter-one__text">
                        <span class="d-block one">Dans plus de</span>
                        <span class="d-block font-weight-bold two">{{ countries }} Pays</span>
                    </p>
                </li>
                <li class="col-md col-6 consultantsCount">
                    <p class="counter-one__text">
                        <span class="d-block one">Avec plus de </span>
                        <span class="font-weight-bold two d-block">{{ consultants }}</span>
                        <span class="three d-block">Experts mobilsés</span>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</section>

templates/foundation/front/embed/default-meta.html.twig
<meta property="og:title" content="{{ 'core.app'|trans({}, 'app') }}">
<meta property="og:description" content="{{ 'core.app'|trans({}, 'app') }}"/>
<meta property="og:type" content="website">
<meta property="og:image" content="{{ absolute_url(asset('assets/images/logo.png')) }}">
<meta property="og:url" content="{{ absolute_url(asset('assets/images/logo.png')) }}">

templates/foundation/front/embed/entities.html.twig
<section class="services-one pb-0">
    <div class="services-one-container">
        {% if enabledTitle %}
            <div class="section-title text-center">
                <h2 class="section-title__title">Quelques expertises des entités du Groupe</h2>
            </div>
        {% endif %}
        <div class="bg-white">
            <div class="container">
                <div class="row h-100">
                    <div class="col-xl-5 col-lg-5 col-12">
                        <!--Services One Single-->
                        <div class="services-one__single entities">
                            {% for item in entities %}
                                <div class="entity desktop d-none d-md-block"
                                     data-uri="{{ path('app_business_front_ajax_entity_services',{'id':item.id}) }}">
                                    <span class="entity-logo">
                                        {% if item.thumbnail is not null and item.thumbnail.imageExists %}
                                            <img data-full-size-image-url="{{ asset(item.thumbnail.webPath) }}"
                                                 src="{{ asset(item.thumbnail.webPath) }}" alt="{{ item.name }}"
                                                 typeof="foaf:Image" class="img-fluid">
                                        {% else %}
                                            <img src="{{ asset('images/blog/news-page-img-1.jpg') }}"
                                                 typeof="foaf:Image" class="img-fluid">
                                        {% endif %}
                                    </span>
                                    <span class="entity-name">{{ item.name }}</span>
                                </div>
                                <a class="entity d-block d-md-none" href="{{ path('app_business_front_group_entity_single',{'id':item.id, 'slug':item.slug}) }}">
                                    <span class="entity-logo">
                                        {% if item.thumbnail is not null and item.thumbnail.imageExists %}
                                            <img data-full-size-image-url="{{ asset(item.thumbnail.webPath) }}"
                                                 src="{{ asset(item.thumbnail.webPath) }}" alt="{{ item.name }}"
                                                 typeof="foaf:Image" class="img-fluid">
                                        {% else %}
                                            <img src="{{ asset('images/blog/news-page-img-1.jpg') }}"
                                                 typeof="foaf:Image" class="img-fluid">
                                        {% endif %}
                                    </span>
                                    <span class="entity-name">{{ item.name }}</span>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-xl-7 col-lg-7 col-12">
                        <div class="d-none d-md-block">
                            <!--Services One Single-->
                            <div class="services-one__single service-right-desc" id="entity-services">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/foundation/front/embed/header.html.twig
<header class="main-header clearfix">
    <div class="main-header__three-line-icon">
        <a href="#" class="side-menu__toggler">
            <img src="{{ asset('images/resources/main-header-three-line-icon.png') }}" alt="">
        </a>
    </div>
    <div class="main-menu-wrapper">
        <div class="main-menu-wrapper__top">
            <div class="container">
                <div class="main-menu-wrapper__top-inner">
                    <div class="main-menu-wrapper__left">
                        <div class="main-menu-wrapper__left-content">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle btn-find" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    Vous êtes intéressé par ? <span class="arrow-icon"><i class="arrow-down"></i></span>
                                </button>
                                <ul class="dropdown-menu top-dropdown-menu expertises-menu" aria-labelledby="dropdownMenuButton1">
                                    {% for item in expertises %}
                                        <li>
                                            <a class="dropdown-item" href="#{{ path('app_business_front_expertise_single',{'id':item.id,'slug':item.i18n(locale).slug}) }}">
                                                {{ item.i18n(locale).name }}
                                                <span class="chevron-menu"> <i class="ik ik-chevron-right"></i></span>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <p class="call-us">
                                <span class="call-us-text">
                                    Appelez au :
                                </span>{{ numtel }}
                            </p>
                        </div>
                    </div>
                    <div class="main-menu-wrapper__center">
                        <div class="main-menu-wrapper__center-content">
                            <div class="main-header__logo">
                                <a href="{{ path('app_foundation_front_homepage') }}">
                                    <img src="{{ asset('images/logo.png') }}" class="img-fluid" alt="">
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="main-menu-wrapper__right">
                        <span class="li">
                            <i class="ik ik-search search-icon"></i>
                        </span>
                        <span class="li">
                            <a href="{{ path('app_business_front_consultation') }}" class="btn btn-top text-uppercase">Consultation</a>
                        </span>
                        <span class="li">
                            <a href="{{ path('app_business_front_quotation') }}" class="btn btn-top text-uppercase">Devis en ligne</a>
                        </span>
                        <span class="li">
                            {{ render(controller("App\\Controller\\Foundation\\Front\\EmbedController::languages")) }}
                        </span>
{#                        <span class="li">#}
{#                            <span class="text d-flex">#}
{#                                {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}#}
{#                                    <a class="myspace-btn" href="{{ path('app_back_dashboard') }}">#}
{#                                        <span class="starsmall-white"></span> <span class="my">Mon</span> Bureau#}
{#                                    </a>#}
{#                                    <a class="exhibit" href="{{ path('app_user_front_logout') }}">#}
{#                                        {{ 'core.sing-off'|trans({}, 'app') }}#}
{#                                    </a>#}
{#                                {% else %}#}
{#                                    <a class="text-yellow" href="{{ path('app_user_front_login') }}">#}
{#                                        {{ 'core.sing-in'|trans({}, 'app') }}#}
{#                                    </a>#}
{#                                {% endif %}#}
{#                            </span>#}
{#                        </span>#}
                    </div>
                </div>
            </div>
        </div>
        <div class="main-menu-wrapper__bottom">
            <div class="container">
                <nav class="main-menu">
                    <div class="main-menu__inner">
                        <div class="row no-gutters">
                            <div class="col-12">
                                <div class="main-header__logo d-inline-block d-md-none modile">
                                    <a href="{{ path('app_foundation_front_homepage') }}">
                                        <img src="{{ asset('images/logo.png') }}" class="img-fluid" alt="">
                                    </a>
                                </div>
                                <a href="#" class="mobile-nav__toggler"><i class="fa fa-bars"></i></a>
                                <ul class="main-menu__list">
                                    <li class="menu-item">
                                        <a href="{{ path('app_foundation_front_about') }}">
                                            <span class="d-inline-block">{{ 'La firme' | trans([], 'core') }}</span>
                                        </a>
                                    </li>
                                    <li class="menu-item">
                                        <a href="{{ path('app_business_front_expertises') }}">
                                            <span class="d-inline-block">{{ 'Expertises' | trans([], 'core') }}</span>
                                        </a>
                                    </li>
                                    <li class="menu-item">
                                        <a href="{{ path('app_business_front_advertising_objects') }}">{{ 'Objects publicitaires' | trans([], 'menu') }}</a>
                                    </li>
                                    <li class="menu-item">
                                        <a href="{{ path('app_business_front_projects') }}">{{ 'Projets' | trans([], 'menu') }}</a>
                                    </li>
                                    <li class="menu-item"><a
                                                href="{{ path('app_business_front_customers') }}">{{ 'Clients' | trans([], 'menu') }}</a>
                                    </li>
                                    <li class="menu-item"><a
                                                href="{{ path('app_blog_front_galleries') }}">{{ 'Gallery' | trans([], 'menu') }}</a>
                                    </li>
                                    <li class="menu-item"><a
                                                href="{{ path('app_blog_front_posts') }}">{{ 'news' | trans([], 'menu') }}</a>
                                    </li>
                                    <li class="menu-item"><a
                                                href="{{ path('app_foundation_front_contact') }}">{{ 'contact' | trans([], 'menu') }}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="stricky-header stricked-menu main-menu">
    <div class="sticky-header__content"></div><!-- /.sticky-header__content -->
</div><!-- /.stricky-header -->

templates/foundation/front/embed/posts.html.twig
<section class="news-one">
    <div class="container">
        <div class="section-title text-center">
            <h2 class="products-title"><span class="circle-mark"></span> L'actualité <span class="font-light">de votre firme</span></h2>
        </div>
        <div class="row">
            {% for item in entities %}
                <div class="col-xl-3 col-lg-3 col-12 wow fadeInUp" data-wow-delay="100ms">
                    <!--News One Single-->
                    {% include 'blog/front/post/shared/single.html.twig' with {'item':item} %}
                </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/foundation/front/embed/teams-grid.html.twig
<a id="our-team"></a>
<section data-padding="top" >
    <div class="container">
        <div data-aos="fade" class="row">
            <div class="col-12">
                <div class="sectiontitle-element--center">
                    <span class="toptitle--primary">Notre équipe est constituée des meilleurs</span>
                    <h2>{{'rules.feature_team'| trans([], 'form')}}</h2>
                    <p>Notre equipe d'expert</p>
                </div>
            </div>
        </div>
        <div class="row" data-padding="smtop">
            {% for item in entities %}
                <!--  Single Team  -->
                <div data-aos="fade-up" data-margin="xsbottom" class="col-12 col-xs-6 col-sm-6 col-md-4 col-lg-3">
                    <div class="square-element--overlay">
                        <div class="info">
                            <div class="image">
                                {% if item.thumbnail is not null and item.thumbnail.fileExists %}
                                    <img data-unveil src="#" data-src="{{ asset(item.thumbnail.webPath) }}" data-src-retina="{{  asset(item.thumbnail.webPath) }}" alt="">
                                {% else %}
                                    <img data-unveil src="#" data-src="{{ asset('img/demo/team-1.jpg') }}" data-src-retina="{{ asset('img/demo/team-1@2x.jpg') }}" alt="">
                                {% endif %}
                                <div class="social">
                                    <ul>
                                        <li><a href="{{ item.linkedinLink ? item.linkedinLink : '#' }}" target="_blank" rel="noreferrer"><i class="fab fa-linkedin-in"></i></a></li>
                                        <li><a href="{{ item.twiterLink ? item.twiterLink : '#' }}" target="_blank" rel="noreferrer"><i class="fab fa-twitter"></i></a></li>
                                        <li><a href="{{ item.facebookLink ? 'mailto:'~item.facebookLink : '#' }}" target="_blank"><i class="far fa-envelope"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="text">
                                <h6>{{item.fullname}}</h6>
                                <p>{{item.i18n(locale).name}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!--  END Single Team  -->
            {% endfor %}
        </div>
    </div>
</section>